/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.4.0.0                                               */
/*  Date (dd.mm.yyyy): 21. 2.2024   Time (hh:mm): 14:03                        */
/*******************************************************************************/


#ifndef _GX_WINDOW_DISPLAY_SCREEN_1024X600_RESOURCES_H_
#define _GX_WINDOW_DISPLAY_SCREEN_1024X600_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_SCREEN_1024X600 0
#define DISPLAY_SCREEN_1024X600_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_SCREEN_1024X600_X_RESOLUTION 1024
#define DISPLAY_SCREEN_1024X600_Y_RESOLUTION 600
#define DISPLAY_SCREEN_1024X600_THEME_1 0
#define DISPLAY_SCREEN_1024X600_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_SCREEN_1024X600_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define DISPLAY_SCREEN_1024X600_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define DISPLAY_SCREEN_1024X600_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define DISPLAY_SCREEN_1024X600_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define DISPLAY_SCREEN_1024X600_STRING_TABLE_SIZE 3

#endif                                       /* sentry                         */
